-- AlterTable
ALTER TABLE "menu_recommendation_days" ADD COLUMN     "eaten_carb_g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "eaten_energy_kcal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "eaten_fat_g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "eaten_fiber_g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "eaten_protein_g" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "eaten_sodium_mg" DOUBLE PRECISION NOT NULL DEFAULT 0;
